Add Navbar component and integrate into Layout
talmosko/lotechni.dev pull request #14
Opened 2024-12-26 21:37 UTC by MeirJC

- Created a new Navbar component with responsive design and mobile menu functionality.
- Integrated Navbar into the main Layout, ensuring it appears on all pages.
- Updated navigation links with Hebrew labels for better localization.
- Implemented scroll behavior to hide/show the navbar based on user scroll actions.

Previews:
![image](https://github.com/user-attachments/assets/48a73452-5753-4071-97ab-8582ca53f328)
![image](https://github.com/user-attachments/assets/6d426c23-fb8a-4055-977f-db37a406ccbd)
![image](https://github.com/user-attachments/assets/d6b77162-6d57-47fd-a57b-604f76aeb0a7)

2025-01-01 19:32 UTC, talmosko commented on src/components/astro/Navbar.astro
> +          format="webp"
it seems on the photo like the quality of the small size isn't so good
@MeirJC WDYT?

2025-01-01 19:33 UTC, talmosko requested changes
thanks!
@MeirJC small thing to check up (maybe not code)

2025-01-01 19:38 UTC, MeirJC commented on src/components/astro/Navbar.astro
> +          format="webp"
No problem, I'll take care of it tomorrow.
Astro Image automatically optimizes the image. Easy fix is either specify `quality=max (or value of 1-100)`
Or increase the width and height so it scales down better.

2025-01-05 12:48 UTC, MeirJC commented on src/components/astro/Navbar.astro
> +          format="webp"
Hey @talmosko 
I have updated the image quality and size.
The logo i small to be very readable with the small letters.
it's cool for now, but maybe we can have the same styling of text and use that, or get an svg of the text only.

2025-01-05 16:50 UTC, MeirJC commented
@talmosko 
Fixed the image issues (and left a comment of maybe use a better option)

anything else to fix here?

2025-01-05 19:48 UTC, Sa-ar commented on src/layouts/Layout.astro
> +      font-family: 'Rubik Variable', sans-serif;
Why twice?

2025-01-06 08:18 UTC, MeirJC commented on src/layouts/Layout.astro
> +      font-family: 'Rubik Variable', sans-serif;
@Sa-ar you are absolutely right, i guess it was duplicated unintentionally while refactoring.
All this style section has been minimized even more and this line wont be there after my last 2 pr's would be merged. 

we kept these while refactoring from css to tailwind.

anyway, will be fixed in a few minutes.

2025-01-06 08:42 UTC, MeirJC commented on src/layouts/Layout.astro
> +      font-family: 'Rubik Variable', sans-serif;
Done. removed the duplicated line.

2025-01-06 09:00 UTC, talmosko approved these changes
Thanks! 👑

2025-01-06 09:50 UTC, merged