feat: create community component
talmosko/lotechni.dev pull request #15
Opened 2024-12-31 09:13 UTC by Shmuelmb

Create community component responsive layout

2025-01-01 19:36 UTC, talmosko commented on src/components/astro/CommunityCard.astro
> +      'https://pps.whatsapp.net/v/t61.24694-24/437708221_456588560461081_4651990565380993545_n.jpg?ccb=11-4&oh=01_Q5AaIKIyffpZCpof_MhuwdDBiYWK9jHxJTc2R5OFg5BOoTQY&oe=677F8734&_nc_sid=5e03e0&_nc_cat=1
please download and add the assets to the project.

I think that each community needs:
1. an image
2. title (name)
3. short description
4. a button with a link to the community


could you modify the design? Thanks!

@Shmuelmb

2025-01-01 19:36 UTC, talmosko requested changes
Thanks!

see my comment

2025-01-01 19:44 UTC, Shmuelmb commented on src/components/astro/CommunityCard.astro
> +      'https://pps.whatsapp.net/v/t61.24694-24/437708221_456588560461081_4651990565380993545_n.jpg?ccb=11-4&oh=01_Q5AaIKIyffpZCpof_MhuwdDBiYWK9jHxJTc2R5OFg5BOoTQY&oe=677F8734&_nc_sid=5e03e0&_nc_cat=1
Sure, not problem

2025-02-13 05:33 UTC, talmosko approved these changes
@Shmuelmb 👑

2025-02-13 05:35 UTC, merged