Css/Tailwind - refactor and clean - session 01
talmosko/lotechni.dev pull request #3
Opened 2024-12-19 15:10 UTC by MeirJC

This pull request focuses on migrating from traditional CSS to Tailwind CSS across multiple components. The changes involve cleaning up legacy CSS styles and replacing them with Tailwind's utility classes for a more maintainable and consistent styling approach.

### 🛠️ Fixes and Updates:
* Corrected import paths from `@asstes` to `@assets` in multiple files (`README.md`, `src/components/Logo.astro`, `src/components/Speakers.astro`).

### 🎨 CSS to Tailwind:
* Updated `DescriptionCard.astro`, `Logo.astro`, `Speakers.astro` and `Layout.astro` to use Tailwind CSS classes for styling instead of custom CSS.

### ⚙️ Configuration and Dependencies:
* Added `@tailwindcss/typography` to `devDependencies` in `package.json`.
* Updated `tailwind.config.mjs` to include new font families, container padding, and custom colors.

2024-12-22 11:30 UTC, talmosko commented on src/components/SectionContainer.astro
> +const { outerClasses, innerClasses, ...rest } = Astro.props;
is there a reason for that? 
@MeirJC

2024-12-22 11:33 UTC, talmosko requested changes
@MeirJC Thanks Aluf!

see minor comments

2024-12-22 11:34 UTC, talmosko requested changes

2024-12-22 11:34 UTC, talmosko commented on tailwind.config.mjs
> +          light: "oklch(85.93% 0.063 195.95)", // Previous #ABDBDD
just wondering why not HEX :)

2024-12-22 15:21 UTC, MeirJC commented on src/components/SectionContainer.astro
> +const { outerClasses, innerClasses, ...rest } = Astro.props;
Yes, we might no use it. but in case we would like to pass any other attribute that dont have a specific prop.

like if you want to have specific section with id="special-section" you can just pass it as a prop even that we dont have a dedicated id prop.

like this:
`<SectionContainer innerClasses="flex" outerClasses="bg-red-300" id="special-section" />`

Just to have it more flexible, this is known pattern. we can also remove it if we will now use it. nothing critical.

2024-12-22 15:29 UTC, MeirJC commented on tailwind.config.mjs
> +          light: "oklch(85.93% 0.063 195.95)", // Previous #ABDBDD
This is the more modern approach. but nothing critical.
gradients using oklch are smoother, colors are a bit "deeper" (it uses a different colorspace compared to hex/rgb)

and with tailwind 4 this would also be the standard for their setting too, so we are ready if will migrate and we won't need to convert them again.

you can red more here:
[Tailwind V4 Colorspace](https://tailwindcss.com/docs/v4-beta#modernized-p3-color-palette)
[oklch-in-css-why-quit-rgb-hsl](https://evilmartians.com/chronicles/oklch-in-css-why-quit-rgb-hsl)

2024-12-22 16:30 UTC, talmosko commented on tailwind.config.mjs
> +          light: "oklch(85.93% 0.063 195.95)", // Previous #ABDBDD
Thanks! @MeirJC always learning something new

2024-12-22 16:31 UTC, talmosko commented on src/components/SectionContainer.astro
> +const { outerClasses, innerClasses, ...rest } = Astro.props;
@MeirJC yes of course.
I prefer to not do that, and fit the `SectionContainer` itself in the future if needed

2024-12-22 18:51 UTC, MeirJC commented on src/components/SectionContainer.astro
> +const { outerClasses, innerClasses, ...rest } = Astro.props;
@talmosko Done 🤙
merged, solved conflicts and pushed.

2024-12-23 06:08 UTC, talmosko commented
@MeirJC conflicts

2024-12-23 21:04 UTC, meirjc-adzz commented
@talmosko 
Hey, any more issues with this?
many changes from here are needed for moving on.

2024-12-24 15:44 UTC, merged